spring:
  cloud:
    config:
      enabled: false
  main:
    allow-circular-references: true
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

aop:
  logging:
    enabled: true

exception:
  handling:
    enabled: false